//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp.DataAccess.DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ContinentId { get; set; }
        public string Name { get; set; }
    
        public virtual Continent Continent { get; set; }
    }
}
